# Generated by Django 4.1.2 on 2022-10-18 20:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=256)),
                ('message_created_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_title', models.CharField(max_length=32)),
                ('chat_description', models.TextField(null=True)),
                ('chat_created_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('chat_message', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chats.message')),
            ],
        ),
    ]
