# Generated by Django 4.1.2 on 2022-11-14 20:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_title', models.CharField(max_length=32, verbose_name='Название чата')),
                ('chat_description', models.TextField(blank=True, null=True, verbose_name='Описание чата')),
                ('chat_created_at', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Дата создания чата')),
            ],
            options={
                'verbose_name': 'Чат',
                'verbose_name_plural': 'Чаты',
                'ordering': ('-chat_created_at',),
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=256, verbose_name='Текст сообщения')),
                ('message_created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время создания сообщения')),
                ('checked', models.BooleanField(default=False, verbose_name='Сообщение прочитано/нет')),
                ('message_in_chat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='chats.chat', verbose_name='Чат, к которому относится сообщение')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ('-message_created_at',),
            },
        ),
    ]
