# Generated by Django 4.1.2 on 2022-10-25 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='chat_message',
        ),
        migrations.AddField(
            model_name='message',
            name='message_in_chat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chats.chat'),
        ),
    ]
