# Generated by Django 4.1.2 on 2022-11-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='chat_title',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Название чата'),
        ),
    ]
