# Generated by Django 4.1.2 on 2022-12-11 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_alter_chat_chat_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='owner',
            field=models.TextField(default='me', verbose_name='Автор сообщения'),
        ),
    ]
