# Generated by Django 4.1.2 on 2022-12-14 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0006_alter_chat_last_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='last_message_check',
            field=models.BooleanField(default=False, verbose_name='Статус последнего сообщения в чате'),
        ),
        migrations.AddField(
            model_name='chat',
            name='last_message_time',
            field=models.DateTimeField(null=True, verbose_name='Время последнего сообщения в чате'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='last_message',
            field=models.CharField(max_length=256, null=True, verbose_name='Последнее сообщение в чате'),
        ),
    ]
