# Generated by Django 4.1.2 on 2022-12-14 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0007_chat_last_message_check_chat_last_message_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='last_message_owner',
            field=models.CharField(default='me', max_length=100, verbose_name='Автор последнего сообщения в чате'),
        ),
    ]
