# Generated by Django 4.1.2 on 2022-11-14 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_chats',
            field=models.ManyToManyField(blank=True, related_name='user_chats', to='chats.chat', verbose_name='Чаты пользователя'),
        ),
    ]
