# Generated by Django 4.1.2 on 2022-12-05 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_alter_chat_chat_title'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chats_admin',
            field=models.ManyToManyField(blank=True, null=True, related_name='admins', to='chats.chat', verbose_name='Админ в чатах'),
        ),
    ]
