# Generated by Django 4.1.2 on 2022-12-11 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_message_owner'),
        ('users', '0002_user_chats_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='chats_admin',
            field=models.ManyToManyField(blank=True, related_name='admins', to='chats.chat', verbose_name='Админ в чатах'),
        ),
    ]
